### ISSUE TITLE
Solution for Autopkgr with JSS 9.7.2 on sslv3 handshake failure issue

### ISSUE THREAD

**Issue by dalmatian1231** [lindegroup/autopkgr#418]
We have new released AutoPkgr 1.3 working with JSS 9.7.2.  I've seen the following error for many times whenever i tired to run recipe
A Python exception occurred during the execution of autopkg, see the system log for more details.
[ERROR] jss.contrib.requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

i followed the instruction(https://wimacguy.wordpress.com/2014/11/10/how-to-repair-most-sslv3-issues-with-autopkgr-and-a-jss-with-a-self-signed-cert/) by importing PROTOCOL_TLSv1 in addition to PROTOCOL_SSLv23. and changed return PROTOCOL_SSLv23 to return PROTOCOL_TLSv1 in 2 ssl_.py profiles in both jss.py in python_jss-1.2.0-py2.7.egg and python_jss-1.2.1-py2.7.egg.

then make sure the certificate in stored in the keychain, if not, download the certificate from JSS webUI and install it on the autopkgr host.

above 2 steps are the 2 common solution u could find online. but with Jss9.7.2 , sheagcraig suggested me to comment out "self.session.mount(...)" in jss.py as well, as ciphers will still use sslv23 by default if u don't have cipher transport adapter.

so that makes the sslv3 handshake error pass.

**Comment by homebysix** [comment]
Hi @dalmatian1231, thanks for sharing. I guess I'm a little unclear on whether you're claiming this is an AutoPkgr problem/solution or a python-jss problem/solution. Is AutoPkgr involved?
